trainset:
  name: dsecpreprocesstrain
  root_dir: datasets/DSEC
  split: train
  data_seq: full
  isbi: false
  n_workers: 6
  drop_last: false

  max_depth: 35
  max_flow: 100
  max_3dflow: 2.0
  n_points: 8192

  use_preprocess: true
  event_bins: 10
  event_polarity: true

  augmentation:
    enabled: true
    color_jitter:
      enabled: true
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.127  # 0.4/3.14
    random_horizontal_flip:
      enabled: true
    random_vertical_flip:
      enabled: false
    random_crop:
      enabled: false
    random_scale:
      enabled: false
      scale_range: [1.0, 1.5]

valset:
  name: dsecpreprocesstrain
  root_dir: datasets/DSEC
  split: val
  data_seq: full
  isbi: false

  n_workers: 3
  max_depth: 35
  max_flow: 100
  max_3dflow: 2.0
  n_points: 8192

  use_preprocess: true
  event_bins: 10
  event_polarity: true

  augmentation:
    enabled: false

model:
  name: RPEFlow
  batch_size: 12
  freeze_bn: false

  ids:
    enabled: true
    sensor_size_divisor: 32

  attention:
    norm: WithBias # BiasFree
    attention: mdta
    layers: 2

  ids:
    enabled: true
    sensor_size_divisor: 32

  pwc2d:
    event_bins: 10
    event_polarity: true

    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

training:
  max_epochs: 300
  optimizer: adam
  lr:
    scheduler: 'MultiStepLR'
    init_value: 0.0001
    momentum: 0.9

    decay_rate: 0.5
    decay_milestones: [150, 250]
  weight_decay: 0.000001
  bias_decay: 0.0

log:
  dir: outputs/RPEFlow_DSECft_gpu4xbs3
  run_name: RPEFlow_DSECft_gpu4xbs3
  save_ckpt: true
  save_ckpt_every_n_epochs: 1
  save_summary_every_n_steps: 100

ckpt:
  path: null
  resume: false

port: random  # for multi-gpu training
amp: false
