trainset:
  name: kubric
  root_dir: ./datasets/ekubric
  split: train
  n_workers: 6
  drop_last: true

  n_points: 8192
  max_flow: 250.0
  max_depth: 90.0
  max_3dflow: 5.0

  event_bins: 10
  event_polarity: true

  augmentation:
    enabled: true
    color_jitter:
      enabled: false
    random_horizontal_flip:
      enabled: true
    random_vertical_flip:
      enabled: true
    random_crop:
      enabled: false
    random_scale:
      enabled: false

valset:
  name: kubric
  root_dir: ./datasets/ekubric
  split: val
  n_workers: 3

  n_points: 8192
  max_flow: 250.0
  max_depth: 90.0
  max_3dflow: 5.0

  event_bins: 10
  event_polarity: true

  augmentation:
    enabled: false

model:
  name: RPEFlow
  batch_size: 12
  freeze_bn: false

  ids:
    enabled: true
    sensor_size_divisor: 32

  attention:
    norm: WithBias # BiasFree
    attention: mdta
    layers: 2

  pwc2d:
    event_bins: 10
    event_polarity: true
    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

training:
  max_epochs: 300
  optimizer: adam
  lr:
    scheduler: 'MultiStepLR'
    init_value: 0.0001
    momentum: 0.9
    decay_rate: 0.5
    decay_milestones: [150, 250]
  weight_decay: 0.000001
  bias_decay: 0.0

log:
  dir: outputs/RPEFlow_EKubricft_gpu4xbs3
  run_name: RPEFlow_EKubricft_gpu4xbs3
  save_ckpt: true
  save_ckpt_every_n_epochs: 1
  save_summary_every_n_steps: 100

ckpt:
  path: null
  resume: false

port: random  # for multi-gpu training
amp: false
